# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20170825_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('poop', models.BooleanField(verbose_name='Poop')),
                ('pee', models.BooleanField(verbose_name='Urine')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='feeding',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='formula',
            field=models.IntegerField(default=0, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='left',
            field=models.IntegerField(default=0, verbose_name='Left Breast'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='pumped',
            field=models.IntegerField(default=0, verbose_name='Pumped Breastmilk'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='right',
            field=models.IntegerField(default=0, verbose_name='Right Breast'),
        ),
    ]
